import type { Food, MealType } from "@/types/food";

/**
 * 种子食物数据
 * 面向中国大学生日常场景：食堂、外卖、宿舍速食。
 * 老虎机三轴：前两轴从 kind === "main" 抽，第三轴从 kind === "drink" 抽。
 * recipe 用于「附近买不到 → 自己动手」栏。
 * meals 标注适合的餐段，老虎机按当前餐段硬过滤。
 * 后续可替换为接口数据，结构保持一致即可。
 */
export const foods: Food[] = [
  // ===== 具体菜品 dish（108）=====
  {
    id: "huangmen-ji-rice",
    name: "黄焖鸡米饭",
    entityType: "dish",
    shopKeyword: "黄焖鸡",
    emoji: "🍗",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "下饭", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 5,
    description: "鸡肉炖得软烂入味，汤汁拌饭能多吃一碗。",
  },
  {
    id: "lanzhou-beef-noodle",
    name: "兰州牛肉面",
    entityType: "dish",
    shopKeyword: "兰州拉面",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "快手", "高蛋白"],
    regions: ["xibei"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 5,
    description: "清汤萝卜配劲道面条，一碗下肚浑身舒坦。",
  },
  {
    id: "shaxian-wonton",
    name: "沙县馄饨",
    entityType: "dish",
    shopKeyword: "沙县小吃",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["清淡", "省钱", "暖胃"],
    meals: ["breakfast", "lunch", "dinner", "midnight"],
    recommend: 4,
    description: "皮薄馅嫩，便宜又暖胃，随时来一碗都合适。",
  },
  {
    id: "egg-fried-rice",
    name: "蛋炒饭",
    entityType: "dish",
    emoji: "🍳",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "省钱", "适合宿舍"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "隔夜饭加个蛋，几分钟就能炒出一锅香。",
  },
  {
    id: "instant-noodle",
    name: "泡面加蛋",
    entityType: "dish",
    emoji: "🍥",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["适合宿舍", "快手", "省钱"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "懒得做饭时，加个蛋加根肠就很满足。",
    shopKeyword: "便利店",
  },
  {
    id: "guobaorou",
    name: "锅包肉盖饭",
    entityType: "dish",
    emoji: "🍖",
    kind: "main",
    cuisine: "cn-dongbei",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "下饭", "解馋"],
    regions: ["dongbei"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "外脆里嫩、酸甜开胃，东北人从小吃到大。",
  },
  {
    id: "tomato-egg-rice",
    name: "番茄炒蛋盖饭",
    entityType: "dish",
    emoji: "🍅",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "快手", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "酸甜下饭，怎么做都不会出错的家常味。",
    shopKeyword: "盖浇饭",
  },
  {
    id: "porridge-set",
    name: "皮蛋瘦肉粥",
    entityType: "dish",
    emoji: "🥣",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "暖胃", "健康轻食"],
    meals: ["breakfast", "midnight"],
    recommend: 3,
    description: "熬夜或没胃口的时候，喝一碗暖暖的很舒服。",
  },
  {
    id: "chicken-breast-salad",
    name: "鸡胸肉沙拉",
    entityType: "dish",
    emoji: "🥗",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "高蛋白", "清淡"],
    meals: ["lunch", "dinner", "tea"],
    recommend: 3,
    description: "清爽少负担，想吃得健康点时的稳妥选择。",
    shopKeyword: "沙拉",
  },
  {
    id: "jianbing",
    name: "煎饼果子",
    entityType: "dish",
    shopKeyword: "煎饼果子",
    emoji: "🫓",
    kind: "main",
    cuisine: "cn-beifang",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "省钱", "解馋"],
    regions: ["beifang"],
    meals: ["breakfast", "lunch"],
    recommend: 4,
    description: "加俩蛋加薄脆，路边买一个边走边吃。",
  },
  {
    id: "roujiamo",
    name: "肉夹馍",
    entityType: "dish",
    shopKeyword: "肉夹馍",
    emoji: "🥙",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["快手", "解馋", "高热量"],
    regions: ["xibei"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "馍香肉烂，单手就能拿着吃，方便又顶饱。",
  },
  {
    id: "dumplings",
    name: "速冻饺子",
    entityType: "dish",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["适合宿舍", "快手", "暖胃"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "煮一锅蘸点醋，简单又顶饱的一餐。",
    shopKeyword: "饺子",
  },
  {
    id: "kungpao-chicken-rice",
    name: "宫保鸡丁盖饭",
    entityType: "dish",
    emoji: "🍱",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["下饭", "高蛋白", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "酸甜微辣带花生，食堂里常点的那一款。",
  },
  {
    id: "hot-dry-noodle",
    name: "热干面",
    entityType: "dish",
    shopKeyword: "热干面",
    emoji: "🍝",
    kind: "main",
    cuisine: "cn-beifang",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "解馋", "省钱"],
    regions: ["beifang"],
    meals: ["breakfast", "lunch"],
    recommend: 4,
    description: "芝麻酱拌开，武汉人早餐桌上的常客。",
  },
  {
    id: "stir-fry-broccoli",
    name: "西兰花炒虾仁",
    entityType: "dish",
    emoji: "🥦",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "高蛋白", "清淡"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "清淡又有营养，吃着没负担。",
    shopKeyword: "家常菜",
  },
  {
    id: "youtiao",
    name: "油条",
    entityType: "dish",
    emoji: "🥖",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "省钱", "解馋"],
    meals: ["breakfast"],
    recommend: 4,
    description: "金黄酥脆，配碗豆浆就是经典早餐。",
  },
  {
    id: "doufunao",
    name: "豆腐脑",
    entityType: "dish",
    emoji: "🥣",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["清淡", "暖胃", "健康轻食"],
    meals: ["breakfast"],
    recommend: 3,
    description: "嫩得入口即化，甜的咸的都好吃。",
  },
  {
    id: "xiaolongbao",
    name: "小笼包",
    entityType: "dish",
    shopKeyword: "小笼包",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-jiangzhe",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "暖胃", "高蛋白"],
    regions: ["jiangzhe"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 4,
    description: "皮薄汤多，轻轻咬开先喝口汤，小心烫。",
  },
  {
    id: "guilin-rice-noodle",
    name: "桂林米粉",
    entityType: "dish",
    shopKeyword: "桂林米粉",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-yunguigui",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "省钱", "暖胃"],
    regions: ["yunguigui"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "拌着卤水嗦一碗，米粉爱好者的早餐。",
  },
  {
    id: "chongqing-xiaomian",
    name: "重庆小面",
    entityType: "dish",
    shopKeyword: "小面",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["快手", "解馋", "暖胃"],
    regions: ["chuanyu"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "麻辣鲜香的一碗素面，早上吃很提神。",
  },
  {
    id: "lu-rou-fan",
    name: "卤肉饭",
    entityType: "dish",
    shopKeyword: "卤肉饭",
    emoji: "🍚",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "解馋", "高热量"],
    meals: ["lunch", "dinner"],
    recommend: 5,
    description: "酱香卤肉淋在饭上，忍不住多扒两口。",
  },
  {
    id: "yuxiang-rousi-rice",
    name: "鱼香肉丝盖饭",
    entityType: "dish",
    emoji: "🍱",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["下饭", "解馋", "高蛋白"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "酸甜咸辣都有，特别下饭。",
  },
  {
    id: "luosifen",
    name: "螺蛳粉",
    entityType: "dish",
    shopKeyword: "螺蛳粉",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-yunguigui",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高热量", "适合宿舍"],
    regions: ["yunguigui"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "闻着冲、吃着香，嗦粉爱好者懂的。",
  },
  {
    id: "ganchao-niuhe",
    name: "干炒牛河",
    entityType: "dish",
    emoji: "🍳",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "下饭"],
    regions: ["guangdong"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "镬气十足的粤式经典，滑而不腻。",
    shopKeyword: "茶餐厅",
  },
  {
    id: "xiaolongxia",
    name: "麻辣小龙虾",
    entityType: "dish",
    shopKeyword: "小龙虾",
    emoji: "🦞",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "treat",
    spicy: 3,
    tags: ["高热量", "解馋"],
    meals: ["dinner", "midnight"],
    recommend: 5,
    description: "夏天剥虾配冰啤，越吃越上瘾。",
  },
  {
    id: "kao-leng-mian",
    name: "烤冷面",
    entityType: "dish",
    shopKeyword: "烤冷面",
    emoji: "🍳",
    kind: "main",
    cuisine: "cn-dongbei",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "解馋", "省钱"],
    regions: ["dongbei"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "酸甜辣都有，东北街边的小吃。",
  },
  {
    id: "suanla-fen",
    name: "酸辣粉",
    entityType: "dish",
    shopKeyword: "酸辣粉",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "budget",
    spicy: 2,
    tags: ["解馋", "暖胃", "适合宿舍"],
    regions: ["chuanyu"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "酸辣开胃，红薯粉爽滑弹牙。",
  },
  {
    id: "liangpi",
    name: "凉皮",
    entityType: "dish",
    shopKeyword: "凉皮",
    emoji: "🥗",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["清淡", "解腻", "快手"],
    regions: ["xibei"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "夏天没胃口时，酸辣一碗很开胃。",
  },
  {
    id: "shaguo-mixian",
    name: "砂锅米线",
    entityType: "dish",
    shopKeyword: "砂锅米线",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["暖胃", "解馋", "高热量"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "热腾腾一砂锅，冷天吃最舒服。",
  },
  {
    id: "egg-tart",
    name: "蛋挞",
    entityType: "dish",
    emoji: "🥧",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "快手"],
    meals: ["tea", "breakfast"],
    recommend: 4,
    description: "酥皮咬下去咔嚓一声，下午茶的经典。",
  },
  {
    id: "waffle",
    name: "华夫饼",
    entityType: "dish",
    emoji: "🧇",
    kind: "main",
    cuisine: "western-american",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "快手"],
    meals: ["tea", "breakfast"],
    recommend: 3,
    description: "格子里淋满糖浆，喜欢甜的会很满足。",
    shopKeyword: "甜品",
  },
  {
    id: "soup-dumpling-pan",
    name: "生煎包",
    entityType: "dish",
    shopKeyword: "生煎",
    emoji: "🍤",
    kind: "main",
    cuisine: "cn-jiangzhe",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高热量", "快手"],
    regions: ["jiangzhe"],
    meals: ["breakfast", "tea", "lunch"],
    recommend: 4,
    description: "底脆顶松还带汤，上海经典早点。",
  },
  {
    id: "tangyuan",
    name: "汤圆",
    entityType: "dish",
    emoji: "🍡",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "暖胃"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "软糯流心，吃一碗整个人都暖了。",
  },
  {
    id: "fries",
    name: "薯条",
    entityType: "dish",
    emoji: "🍟",
    kind: "main",
    cuisine: "western-american",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "快手"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 4,
    description: "金黄酥脆蘸番茄酱，配什么都香。",
  },
  {
    id: "takoyaki",
    name: "章鱼小丸子",
    entityType: "dish",
    emoji: "🐙",
    kind: "main",
    cuisine: "japanese",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "快手"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 3,
    description: "外软内嫩，淋满酱汁撒上木鱼花。",
  },
  {
    id: "fried-rice-noodle-singapore",
    name: "星洲炒米粉",
    entityType: "dish",
    emoji: "🍛",
    kind: "main",
    cuisine: "sea",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "下饭", "快手"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "咖喱味十足，米粉根根分明。",
  },
  {
    id: "cold-noodle-korean",
    name: "韩式冷面",
    entityType: "dish",
    emoji: "🥶",
    kind: "main",
    cuisine: "korean",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "解腻"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "冰镇酸甜，夏天嗦一碗透心凉。",
  },
  {
    id: "wonton-noodle",
    name: "云吞面",
    entityType: "dish",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "暖胃", "快手"],
    regions: ["guangdong"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "弹牙细面配鲜虾云吞，广式经典。",
  },
  {
    id: "longjiang-pig-feet-rice",
    name: "隆江猪脚饭",
    entityType: "dish",
    shopKeyword: "猪脚饭",
    emoji: "🍖",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "高热量", "解馋"],
    regions: ["guangdong"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "卤香猪脚淋在饭上，胶质满满很扛饿。",
  },
  {
    id: "xiangxi-bucket-rice",
    name: "湘西木桶饭",
    entityType: "dish",
    emoji: "🍚",
    kind: "main",
    cuisine: "cn-hunan",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["下饭", "解馋"],
    regions: ["hunan"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "木桶蒸饭带着饭香，配菜随便挑。",
  },
  {
    id: "suancaiyu-rice",
    name: "酸菜鱼米饭",
    entityType: "dish",
    emoji: "🐟",
    kind: "main",
    cuisine: "cn-hunan",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["下饭", "解馋", "暖胃"],
    regions: ["hunan", "chuanyu"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "酸辣开胃，鱼片嫩滑，汤泡饭很下饭。",
  },
  {
    id: "japanese-beef-rice",
    name: "日式肥牛饭",
    entityType: "dish",
    emoji: "🍱",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "高蛋白", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "洋葱肥牛盖热饭，甜咸酱汁很香。",
    shopKeyword: "日式料理",
  },
  {
    id: "bibimbap",
    name: "韩式石锅拌饭",
    entityType: "dish",
    emoji: "🍲",
    kind: "main",
    cuisine: "korean",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "石锅滋滋响，拌开是焦香的锅巴。",
  },
  {
    id: "curry-chicken-rice",
    name: "咖喱鸡肉饭",
    entityType: "dish",
    emoji: "🍛",
    kind: "main",
    cuisine: "sea",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "解馋", "高热量"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "浓郁咖喱裹着鸡块，浇饭特别下饭。",
    shopKeyword: "咖喱",
  },
  {
    id: "beijing-zhajiang-noodle",
    name: "老北京炸酱面",
    entityType: "dish",
    shopKeyword: "老北京炸酱面",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-beifang",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "解馋"],
    regions: ["beifang"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "一勺炸酱拌到底，菜码越多越好吃。",
  },
  {
    id: "shaanxi-youpo-noodle",
    name: "陕西油泼面",
    entityType: "dish",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "normal",
    spicy: 3,
    tags: ["解馋", "下饭", "高热量"],
    regions: ["xibei"],
    meals: ["lunch", "dinner"],
    recommend: 5,
    description: "滚油泼辣子那一声刺啦，香得很。",
  },
  {
    id: "shanxi-knife-noodle",
    name: "山西刀削面",
    entityType: "dish",
    shopKeyword: "刀削面",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解馋"],
    regions: ["xibei"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "中厚边薄有嚼劲，浇头给得足。",
  },
  {
    id: "tonkotsu-ramen",
    name: "日式豚骨拉面",
    entityType: "dish",
    emoji: "🍜",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解馋", "高热量"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "奶白浓汤配溏心蛋，一口很满足。",
  },
  {
    id: "hunan-beef-noodle",
    name: "湖南牛肉粉",
    entityType: "dish",
    shopKeyword: "湖南牛肉粉",
    emoji: "🍜",
    kind: "main",
    cuisine: "cn-hunan",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["暖胃", "解馋", "下饭"],
    regions: ["hunan"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "红汤米粉嗦一碗，辣得通透又过瘾。",
  },
  {
    id: "crossing-bridge-noodle",
    name: "云南过桥米线",
    entityType: "dish",
    shopKeyword: "过桥米线",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-yunguigui",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["暖胃", "清淡", "解馋"],
    regions: ["yunguigui"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "滚汤现烫食材，吃起来很有仪式感。",
  },
  {
    id: "huainan-beef-soup",
    name: "淮南牛肉汤",
    entityType: "dish",
    shopKeyword: "淮南牛肉汤",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "高蛋白", "清淡"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "咸鲜牛肉汤泡粉丝，早上喝一碗暖到脚。",
  },
  {
    id: "turkish-kebab-rice",
    name: "土耳其烤肉饭",
    entityType: "dish",
    emoji: "🥙",
    kind: "main",
    cuisine: "mideast",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["解馋", "高热量", "下饭"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "现削烤肉铺在饭上，香料味很特别。",
    shopKeyword: "土耳其烤肉",
  },
  {
    id: "huiguorou",
    name: "回锅肉",
    entityType: "dish",
    emoji: "🥓",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["下饭", "解馋", "高热量"],
    regions: ["chuanyu"],
    meals: ["lunch", "dinner"],
    recommend: 5,
    description: "五花肉配蒜苗，川菜里的下饭好手。",
  },
  {
    id: "mapo-tofu",
    name: "麻婆豆腐",
    entityType: "dish",
    emoji: "🌶️",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["下饭", "解馋", "暖胃"],
    regions: ["chuanyu"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "又麻又辣，一块豆腐能配半碗饭。",
  },
  {
    id: "shrimp-dumpling",
    name: "粤式虾饺",
    entityType: "dish",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "解馋"],
    regions: ["guangdong"],
    meals: ["breakfast", "tea", "lunch"],
    recommend: 4,
    description: "皮薄透亮包着整只虾，早茶的招牌。",
    shopKeyword: "粤式点心",
  },
  {
    id: "siumai",
    name: "粤式烧卖",
    entityType: "dish",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "下饭"],
    regions: ["guangdong"],
    meals: ["breakfast", "tea", "lunch"],
    recommend: 3,
    description: "皮薄馅大一口一个，配茶刚好。",
    shopKeyword: "粤式点心",
  },
  {
    id: "dapanji",
    name: "大盘鸡",
    entityType: "dish",
    emoji: "🍗",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["解馋", "下饭", "高热量"],
    regions: ["xibei"],
    meals: ["dinner"],
    recommend: 5,
    description: "鸡块土豆配皮带面，分量足，适合一桌人。",
    shopKeyword: "新疆菜",
  },
  {
    id: "hand-grabbed-lamb",
    name: "手抓羊肉",
    entityType: "dish",
    emoji: "🍖",
    kind: "main",
    cuisine: "cn-xibei",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["高蛋白", "解馋", "暖胃"],
    regions: ["xibei"],
    meals: ["dinner"],
    recommend: 4,
    description: "大块羊肉原汁原味，蘸点椒盐很香。",
  },
  {
    id: "tom-yum-soup",
    name: "泰式冬阴功汤",
    entityType: "dish",
    emoji: "🍤",
    kind: "main",
    cuisine: "thai",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解腻", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "酸辣鲜香带椰味，开胃得很。",
    shopKeyword: "泰国菜",
  },
  {
    id: "maoxuewang",
    name: "重庆毛血旺",
    entityType: "dish",
    emoji: "🌶️",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "treat",
    spicy: 3,
    tags: ["高热量", "解馋", "下饭"],
    regions: ["chuanyu"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "红油一大盆，麻辣鲜烫很过瘾。",
  },
  {
    id: "paper-wrapped-fish",
    name: "纸包鱼",
    entityType: "dish",
    shopKeyword: "纸包鱼",
    emoji: "🐟",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "暖胃", "下饭"],
    meals: ["dinner"],
    recommend: 3,
    description: "锡纸锁住汤汁，鲜辣又不柴。",
  },
  {
    id: "garlic-crayfish",
    name: "蒜香小龙虾",
    entityType: "dish",
    shopKeyword: "小龙虾",
    emoji: "🦐",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["解馋", "高蛋白"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "蒜香不辣，剥起来停不下手。",
  },
  {
    id: "beef-brown-rice",
    name: "低卡牛肉糙米饭",
    entityType: "dish",
    emoji: "🍚",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "高蛋白", "清淡"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "糙米配瘦牛肉，健身的时候吃着踏实。",
    shopKeyword: "轻食沙拉",
  },
  {
    id: "poke-bowl",
    name: "波奇饭",
    entityType: "dish",
    emoji: "🥗",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "清淡", "高蛋白"],
    meals: ["lunch", "tea"],
    recommend: 3,
    description: "生鱼蔬菜拌饭，清爽又轻盈。",
  },
  {
    id: "shuangpinai",
    name: "广式双皮奶",
    entityType: "dish",
    emoji: "🥛",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "清淡", "暖胃"],
    regions: ["guangdong"],
    meals: ["tea", "midnight"],
    recommend: 4,
    description: "奶皮嫩滑入口即化，糖水铺的经典。",
    shopKeyword: "糖水",
  },
  {
    id: "jiangzhuangnai",
    name: "姜撞奶",
    entityType: "dish",
    emoji: "🥛",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解馋", "清淡"],
    regions: ["guangdong"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "姜汁撞热奶凝成冻，暖胃又驱寒。",
    shopKeyword: "糖水",
  },
  {
    id: "grass-jelly",
    name: "烧仙草",
    entityType: "dish",
    emoji: "🍮",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "解腻"],
    meals: ["tea", "midnight"],
    recommend: 4,
    description: "Q弹仙草加满料，夏天一碗很清凉。",
  },
  {
    id: "iced-tangyuan",
    name: "冰汤圆",
    entityType: "dish",
    emoji: "🍡",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "解腻"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "小圆子配冰糖水，甜糯又清凉。",
    shopKeyword: "糖水",
  },
  {
    id: "tujia-sauce-cake",
    name: "土家酱香饼",
    entityType: "dish",
    shopKeyword: "土家酱香饼",
    emoji: "🫓",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "省钱", "快手"],
    meals: ["breakfast", "tea", "lunch"],
    recommend: 4,
    description: "刷满酱料层层酥，街边老远就能闻到香。",
  },
  {
    id: "thousand-layer-cake",
    name: "千层饼",
    entityType: "dish",
    emoji: "🫓",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "省钱", "快手"],
    meals: ["breakfast", "tea"],
    recommend: 3,
    description: "层层起酥咬下掉渣，越嚼越香。",
  },
  {
    id: "meigancai-kuilei",
    name: "梅干菜锅盔",
    entityType: "dish",
    emoji: "🫓",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "省钱"],
    meals: ["breakfast", "tea", "lunch"],
    recommend: 3,
    description: "梅干菜肉炭炉烤脆，外焦里香。",
    shopKeyword: "小吃",
  },
  {
    id: "changsha-stinky-tofu",
    name: "长沙臭豆腐",
    entityType: "dish",
    shopKeyword: "长沙臭豆腐",
    emoji: "🧆",
    kind: "main",
    cuisine: "cn-hunan",
    role: "snack",
    priceTier: "normal",
    spicy: 2,
    tags: ["解馋", "下饭"],
    regions: ["hunan"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 4,
    description: "闻着冲、吃着香，配蒜蓉汁更带劲。",
  },
  {
    id: "chicken-strips",
    name: "无骨鸡柳",
    entityType: "dish",
    emoji: "🍗",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高热量", "快手"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 4,
    description: "现炸鸡柳撒点椒盐，逛街时边走边吃。",
    shopKeyword: "小吃",
  },
  {
    id: "yansuji",
    name: "盐酥鸡",
    entityType: "dish",
    emoji: "🍗",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高热量"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 4,
    description: "九层塔配小块炸鸡，台式夜市的味道。",
  },
  {
    id: "honey-gluten",
    name: "蜜汁烤面筋",
    entityType: "dish",
    emoji: "🍢",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "省钱"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 3,
    description: "甜辣酱刷在烤面筋上，一串接一串。",
    shopKeyword: "小吃",
  },
  {
    id: "red-bean-pie",
    name: "红豆派",
    entityType: "dish",
    emoji: "🥧",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "酥皮裹着红豆沙，热乎乎的甜。",
    shopKeyword: "甜品",
  },
  {
    id: "miso-ramen",
    name: "味噌拉面",
    entityType: "dish",
    emoji: "🍜",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解馋", "高热量"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "味噌汤底醇厚，配上玉米黄油很治愈。",
    shopKeyword: "日式拉面",
  },
  {
    id: "tonkatsu-set",
    name: "日式炸猪排饭",
    entityType: "dish",
    emoji: "🍱",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "外壳酥脆、肉汁饱满，配卷心菜丝解腻。",
    shopKeyword: "日式料理",
  },
  {
    id: "oyako-don",
    name: "亲子丼",
    entityType: "dish",
    emoji: "🍚",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "暖胃", "高蛋白"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "滑蛋裹鸡肉浇在热饭上，温柔好入口。",
    shopKeyword: "日式料理",
  },
  {
    id: "unagi-don",
    name: "鳗鱼饭",
    entityType: "dish",
    emoji: "🍱",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["解馋", "高蛋白", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "蒲烧鳗鱼油亮咸甜，铺满一整碗。",
    shopKeyword: "日式料理",
  },
  {
    id: "matcha-daifuku",
    name: "宇治抹茶大福",
    entityType: "dish",
    emoji: "🍡",
    kind: "main",
    cuisine: "japanese",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "软糯麻薯裹抹茶馅，微苦回甘。",
    shopKeyword: "甜品",
  },
  {
    id: "dorayaki",
    name: "铜锣烧",
    entityType: "dish",
    emoji: "🥞",
    kind: "main",
    cuisine: "japanese",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "快手"],
    meals: ["tea", "breakfast"],
    recommend: 3,
    description: "松软饼皮夹红豆馅，哆啦A梦同款。",
    shopKeyword: "甜品",
  },
  {
    id: "tteokbokki",
    name: "韩式辣炒年糕",
    entityType: "dish",
    emoji: "🌶️",
    kind: "main",
    cuisine: "korean",
    role: "snack",
    priceTier: "budget",
    spicy: 2,
    tags: ["解馋", "下饭"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 4,
    description: "软弹年糕裹满甜辣酱，停不下嘴。",
    shopKeyword: "韩式料理",
  },
  {
    id: "cheese-tteokbokki",
    name: "韩式芝士年糕",
    entityType: "dish",
    emoji: "🧀",
    kind: "main",
    cuisine: "korean",
    role: "snack",
    priceTier: "normal",
    spicy: 2,
    tags: ["解馋", "高热量"],
    meals: ["tea", "dinner", "midnight"],
    recommend: 4,
    description: "甜辣年糕拉满芝士，咸甜辣一口满足。",
    shopKeyword: "韩式料理",
  },
  {
    id: "kimbap",
    name: "韩式紫菜包饭",
    entityType: "dish",
    emoji: "🍙",
    kind: "main",
    cuisine: "korean",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "清淡", "适合宿舍"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 3,
    description: "蔬菜火腿卷进饭里，切片好拿好吃。",
    shopKeyword: "韩式料理",
  },
  {
    id: "jajangmyeon",
    name: "韩式炸酱面",
    entityType: "dish",
    emoji: "🍜",
    kind: "main",
    cuisine: "korean",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "解馋", "高热量"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "黑亮春酱拌粗面，甜咸浓郁很过瘾。",
    shopKeyword: "韩式料理",
  },
  {
    id: "samgyetang",
    name: "韩式参鸡汤",
    entityType: "dish",
    emoji: "🍲",
    kind: "main",
    cuisine: "korean",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["暖胃", "清淡", "高蛋白"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "整只童子鸡炖糯米人参，滋补暖身。",
    shopKeyword: "韩式料理",
  },
  {
    id: "carbonara",
    name: "奶油培根意面",
    entityType: "dish",
    emoji: "🍝",
    kind: "main",
    cuisine: "western-italian",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "蛋黄芝士裹住每根面，咸香浓郁。",
    shopKeyword: "意大利餐厅",
  },
  {
    id: "bolognese",
    name: "经典肉酱意面",
    entityType: "dish",
    emoji: "🍝",
    kind: "main",
    cuisine: "western-italian",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "解馋", "高热量"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "番茄肉酱熬得浓稠，拌面绝配。",
    shopKeyword: "意大利餐厅",
  },
  {
    id: "risotto",
    name: "意式烩饭",
    entityType: "dish",
    emoji: "🍚",
    kind: "main",
    cuisine: "western-italian",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解馋"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "米粒吸饱高汤，奶香芝士很浓郁。",
    shopKeyword: "意大利餐厅",
  },
  {
    id: "steak",
    name: "黑椒牛排",
    entityType: "dish",
    emoji: "🥩",
    kind: "main",
    cuisine: "western-generic",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["高蛋白", "解馋", "高热量"],
    meals: ["dinner"],
    recommend: 4,
    description: "煎到焦香的牛排淋黑椒汁，仪式感拉满。",
    shopKeyword: "牛排",
  },
  {
    id: "caesar-salad",
    name: "凯撒沙拉",
    entityType: "dish",
    emoji: "🥗",
    kind: "main",
    cuisine: "western-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "清淡", "解腻"],
    meals: ["lunch", "tea", "dinner"],
    recommend: 3,
    description: "罗马生菜拌凯撒酱，撒帕玛森和面包丁。",
    shopKeyword: "沙拉",
  },
  {
    id: "fish-and-chips",
    name: "炸鱼薯条",
    entityType: "dish",
    emoji: "🍟",
    kind: "main",
    cuisine: "western-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "酥皮鳕鱼配粗薯条，挤柠檬解腻。",
    shopKeyword: "西餐",
  },
  {
    id: "pancakes",
    name: "美式松饼",
    entityType: "dish",
    emoji: "🥞",
    kind: "main",
    cuisine: "western-american",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "快手"],
    meals: ["breakfast", "tea"],
    recommend: 3,
    description: "叠得高高的松饼淋枫糖浆，配黄油。",
    shopKeyword: "早午餐",
  },
  {
    id: "eggs-benedict",
    name: "班尼迪克蛋",
    entityType: "dish",
    emoji: "🍳",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高蛋白", "解馋"],
    meals: ["breakfast"],
    recommend: 3,
    description: "水波蛋淋荷兰酱，戳开流心配麦芬。",
    shopKeyword: "早午餐",
  },
  {
    id: "hotdog",
    name: "美式热狗",
    entityType: "dish",
    emoji: "🌭",
    kind: "main",
    cuisine: "western-american",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "解馋", "高热量"],
    meals: ["lunch", "tea", "midnight"],
    recommend: 3,
    description: "热狗肠夹软面包，挤满番茄芥末酱。",
    shopKeyword: "便利店",
  },
  {
    id: "buffalo-wings",
    name: "美式炸鸡翅",
    entityType: "dish",
    emoji: "🍗",
    kind: "main",
    cuisine: "western-american",
    role: "snack",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "高热量"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "酸辣水牛城酱裹鸡翅，配蓝纹酱。",
    shopKeyword: "炸鸡",
  },
  {
    id: "pad-thai",
    name: "泰式炒河粉",
    entityType: "dish",
    emoji: "🍤",
    kind: "main",
    cuisine: "thai",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "酸甜花生粉炒河粉，挤青柠更开胃。",
    shopKeyword: "泰国菜",
  },
  {
    id: "pineapple-fried-rice",
    name: "泰式菠萝炒饭",
    entityType: "dish",
    emoji: "🍍",
    kind: "main",
    cuisine: "thai",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "咖喱炒饭装进菠萝盅，酸甜带果香。",
    shopKeyword: "泰国菜",
  },
  {
    id: "green-curry",
    name: "泰式青咖喱鸡",
    entityType: "dish",
    emoji: "🍛",
    kind: "main",
    cuisine: "thai",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["解馋", "暖胃", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "椰浆青咖喱浓香微辣，浇饭一流。",
    shopKeyword: "泰国菜",
  },
  {
    id: "pho",
    name: "越南河粉",
    entityType: "dish",
    emoji: "🍜",
    kind: "main",
    cuisine: "sea",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["清淡", "暖胃", "快手"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "清牛骨汤配嫩牛肉，加豆芽柠檬罗勒。",
  },
  {
    id: "vietnam-banh-mi",
    name: "越南法包",
    entityType: "dish",
    emoji: "🥖",
    kind: "main",
    cuisine: "sea",
    role: "snack",
    priceTier: "budget",
    spicy: 1,
    tags: ["快手", "解馋"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 3,
    description: "脆皮法包夹卤肉腌萝卜香菜，清爽顶饱。",
    shopKeyword: "越南菜",
  },
  {
    id: "nasi-lemak",
    name: "马来椰浆饭",
    entityType: "dish",
    emoji: "🍛",
    kind: "main",
    cuisine: "sea",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "椰香米饭配参巴酱、小鱼花生，南洋风味。",
    shopKeyword: "东南亚菜",
  },
  {
    id: "butter-chicken",
    name: "印度黄油鸡",
    entityType: "dish",
    emoji: "🍛",
    kind: "main",
    cuisine: "exotic-generic",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "暖胃", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "番茄奶油咖喱炖鸡，配馕或米饭都香。",
    shopKeyword: "印度菜",
  },
  {
    id: "curry-naan",
    name: "咖喱飞饼配馕",
    entityType: "dish",
    emoji: "🫓",
    kind: "main",
    cuisine: "exotic-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 1,
    tags: ["解馋", "快手"],
    meals: ["breakfast", "tea", "lunch"],
    recommend: 3,
    description: "烤馕蘸咖喱，层层酥脆带焦香。",
    shopKeyword: "印度菜",
  },
  {
    id: "shawarma",
    name: "中东沙威玛卷",
    entityType: "dish",
    emoji: "🌯",
    kind: "main",
    cuisine: "mideast",
    role: "main",
    priceTier: "budget",
    spicy: 1,
    tags: ["快手", "解馋", "高蛋白"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "现削烤肉裹进薄饼，浇蒜酱包蔬菜。",
    shopKeyword: "中东烤肉",
  },
  {
    id: "falafel",
    name: "中东鹰嘴豆丸",
    entityType: "dish",
    emoji: "🧆",
    kind: "main",
    cuisine: "mideast",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["健康轻食", "解馋"],
    meals: ["lunch", "tea", "dinner"],
    recommend: 3,
    description: "炸鹰嘴豆丸外脆里沙，配芝麻酱很香。",
    shopKeyword: "中东菜",
  },
  {
    id: "burrito",
    name: "墨西哥卷饼",
    entityType: "dish",
    emoji: "🌯",
    kind: "main",
    cuisine: "exotic-generic",
    role: "main",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "下饭", "高热量"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "米饭豆泥牛肉芝士裹成大卷，超扛饿。",
    shopKeyword: "墨西哥菜",
  },
  // ===== 菜品类别 dish_group（17）=====
  {
    id: "fried-chicken",
    name: "炸鸡",
    entityType: "dish_group",
    shopKeyword: "炸鸡",
    emoji: "🍗",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 5,
    description: "外脆里嫩，馋了的时候来一份最解。",
  },
  {
    id: "baozi",
    name: "包子",
    entityType: "dish_group",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "省钱", "暖胃"],
    meals: ["breakfast", "midnight", "tea"],
    recommend: 4,
    description: "热乎乎一笼，咬开满满都是馅。",
  },
  {
    id: "sandwich",
    name: "三明治",
    entityType: "dish_group",
    emoji: "🥪",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["快手", "健康轻食", "适合宿舍"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 3,
    description: "夹料丰富，赶时间也能体面地吃顿早餐。",
  },
  {
    id: "sushi-set",
    name: "寿司拼盘",
    entityType: "dish_group",
    emoji: "🍣",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "清淡", "解馋"],
    meals: ["lunch", "dinner", "tea"],
    recommend: 3,
    description: "清爽不积食，摆盘也好看。",
  },
  {
    id: "burger",
    name: "汉堡",
    entityType: "dish_group",
    emoji: "🍔",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "快手"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "一口下去料满满，简单又满足。",
  },
  {
    id: "pizza",
    name: "披萨",
    entityType: "dish_group",
    emoji: "🍕",
    kind: "main",
    cuisine: "western-italian",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "芝士拉丝，几个人分着吃刚刚好。",
  },
  {
    id: "guandongzhu",
    name: "关东煮",
    entityType: "dish_group",
    emoji: "🍢",
    kind: "main",
    cuisine: "japanese",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "清淡", "解馋"],
    meals: ["dinner", "midnight"],
    recommend: 3,
    description: "便利店里就能买到，深夜来几串暖暖胃。",
    shopKeyword: "便利店",
  },
  {
    id: "cake-slice",
    name: "蛋糕",
    entityType: "dish_group",
    emoji: "🍰",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋"],
    meals: ["tea"],
    recommend: 4,
    description: "一块奶油蛋糕，心情不好时很治愈。",
  },
  {
    id: "cookies",
    name: "曲奇饼干",
    entityType: "dish_group",
    emoji: "🍪",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "适合宿舍"],
    meals: ["tea"],
    recommend: 3,
    description: "配茶配咖啡都行，嘴巴闲不住时来几块。",
    shopKeyword: "便利店",
  },
  {
    id: "claypot-rice",
    name: "煲仔饭",
    entityType: "dish_group",
    shopKeyword: "煲仔饭",
    emoji: "🍚",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["下饭", "高热量", "暖胃"],
    regions: ["guangdong"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "锅巴香脆，腊味的油渗进每粒米。",
  },
  {
    id: "xiang-stirfry",
    name: "湘菜小炒",
    entityType: "dish_group",
    emoji: "🌶️",
    kind: "main",
    cuisine: "cn-hunan",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["下饭", "解馋", "高热量"],
    regions: ["hunan"],
    meals: ["lunch", "dinner"],
    recommend: 5,
    description: "镬气足、辣得香，特别下饭。",
  },
  {
    id: "jiangzhe-stirfry",
    name: "江浙小炒",
    entityType: "dish_group",
    emoji: "🥢",
    kind: "main",
    cuisine: "cn-jiangzhe",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "下饭"],
    regions: ["jiangzhe"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "浓油赤酱偏甜口，温柔的家常味。",
  },
  {
    id: "yakitori",
    name: "日式烧鸟",
    entityType: "dish_group",
    emoji: "🍢",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高蛋白"],
    meals: ["dinner", "midnight"],
    recommend: 3,
    description: "炭火鸡肉串撒点椒盐，小酌时来几串。",
  },
  {
    id: "udon",
    name: "日式乌冬面",
    entityType: "dish_group",
    emoji: "🍜",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["清淡", "暖胃", "快手"],
    meals: ["lunch", "dinner"],
    recommend: 3,
    description: "粗面爽滑，清汤里卧个温泉蛋很舒服。",
    shopKeyword: "日式料理",
  },
  {
    id: "onigiri",
    name: "日式饭团",
    entityType: "dish_group",
    emoji: "🍙",
    kind: "main",
    cuisine: "japanese",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["快手", "清淡", "适合宿舍"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 3,
    description: "海苔包着饭，咬开是三文鱼或梅子。",
    shopKeyword: "便利店",
  },
  {
    id: "tempura",
    name: "天妇罗",
    entityType: "dish_group",
    emoji: "🍤",
    kind: "main",
    cuisine: "japanese",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高热量"],
    meals: ["lunch", "dinner", "tea"],
    recommend: 3,
    description: "薄脆面衣裹虾和蔬菜，蘸天妇罗汁。",
    shopKeyword: "日式料理",
  },
  {
    id: "taco",
    name: "墨西哥塔可",
    entityType: "dish_group",
    emoji: "🌮",
    kind: "main",
    cuisine: "exotic-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 1,
    tags: ["解馋", "快手"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "脆饼壳夹牛肉莎莎酱，一口一个。",
    shopKeyword: "墨西哥菜",
  },
  // ===== 用餐业态 dining_style（21）=====
  {
    id: "malatang",
    name: "麻辣烫",
    entityType: "dining_style",
    shopKeyword: "麻辣烫",
    emoji: "🌶️",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 3,
    tags: ["高热量", "解馋", "暖胃"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 5,
    description: "想吃的菜自己挑，煮一锅热乎乎的。",
  },
  {
    id: "spicy-hot-pot",
    name: "麻辣香锅",
    entityType: "dining_style",
    shopKeyword: "麻辣香锅",
    emoji: "🥘",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 3,
    tags: ["高热量", "解馋", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "食材自选，麻辣干香，几个人分着吃正好。",
  },
  {
    id: "shaokao",
    name: "烧烤",
    entityType: "dining_style",
    shopKeyword: "烧烤",
    emoji: "🍡",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "下饭"],
    meals: ["dinner", "midnight"],
    recommend: 5,
    description: "约上朋友撸串，边吃边聊最放松。",
  },
  {
    id: "northeast-iron-pot",
    name: "东北铁锅炖",
    entityType: "dining_style",
    shopKeyword: "东北铁锅炖",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-dongbei",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["暖胃", "解馋", "下饭"],
    regions: ["dongbei"],
    meals: ["dinner"],
    recommend: 4,
    description: "大锅炖菜贴饼子，一家人围着吃热闹。",
  },
  {
    id: "sichuan-hotpot",
    name: "四川麻辣火锅",
    entityType: "dining_style",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "treat",
    spicy: 3,
    tags: ["高热量", "解馋", "暖胃"],
    regions: ["chuanyu"],
    meals: ["dinner", "midnight"],
    recommend: 5,
    description: "牛油锅底涮一切，约朋友吃热闹。",
    shopKeyword: "火锅",
  },
  {
    id: "chaoshan-beef-hotpot",
    name: "潮汕牛肉火锅",
    entityType: "dining_style",
    emoji: "🐮",
    kind: "main",
    cuisine: "cn-guangdong",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["高蛋白", "清淡", "暖胃"],
    regions: ["guangdong"],
    meals: ["dinner"],
    recommend: 4,
    description: "清汤涮现切牛肉，几秒一夹很鲜。",
    shopKeyword: "牛肉火锅",
  },
  {
    id: "beijing-copper-hotpot",
    name: "老北京铜锅涮肉",
    entityType: "dining_style",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-beifang",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["暖胃", "高蛋白", "解馋"],
    regions: ["beifang"],
    meals: ["dinner"],
    recommend: 4,
    description: "清汤铜锅手切羊肉，麻酱蘸料是关键。",
  },
  {
    id: "chuanchuan",
    name: "九宫格串串香",
    entityType: "dining_style",
    emoji: "🍢",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "snack",
    priceTier: "treat",
    spicy: 2,
    tags: ["解馋", "高热量", "下饭"],
    regions: ["chuanyu"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "一把签子涮到爽，按签子结账。",
    shopKeyword: "串串香",
  },
  {
    id: "frog-fish-hotpot",
    name: "美蛙鱼头火锅",
    entityType: "dining_style",
    shopKeyword: "美蛙鱼头",
    emoji: "🐸",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "treat",
    spicy: 2,
    tags: ["解馋", "高蛋白", "暖胃"],
    regions: ["chuanyu"],
    meals: ["dinner"],
    recommend: 4,
    description: "嫩蛙加鱼头，麻辣锅里的双拼。",
  },
  {
    id: "zhuduji-hotpot",
    name: "猪肚鸡火锅",
    entityType: "dining_style",
    shopKeyword: "猪肚鸡",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["暖胃", "清淡", "高蛋白"],
    meals: ["dinner"],
    recommend: 4,
    description: "胡椒猪肚鸡汤，鲜又养胃，秋冬来一锅。",
  },
  {
    id: "guizhou-sour-hotpot",
    name: "贵州酸汤牛肉火锅",
    entityType: "dining_style",
    shopKeyword: "贵州酸汤牛肉",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-yunguigui",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["暖胃", "解腻", "高蛋白"],
    regions: ["yunguigui"],
    meals: ["dinner"],
    recommend: 4,
    description: "红酸汤开胃，番茄木姜子的香气很特别。",
  },
  {
    id: "rotary-hotpot",
    name: "旋转小火锅",
    entityType: "dining_style",
    shopKeyword: "旋转小火锅",
    emoji: "🍲",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["解馋", "快手", "暖胃"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "一个人也能吃，转盘上夹菜按碟算钱。",
  },
  {
    id: "gutang-maocai",
    name: "骨汤冒菜",
    entityType: "dining_style",
    emoji: "🥣",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "normal",
    spicy: 2,
    tags: ["暖胃", "解馋", "下饭"],
    regions: ["chuanyu"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "一个人的小火锅，连汤带菜一大碗。",
    shopKeyword: "冒菜",
  },
  {
    id: "chinese-charcoal-skewer",
    name: "中式炭烤串",
    entityType: "dining_style",
    emoji: "🍢",
    kind: "main",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "高热量"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "孜然辣椒面撒满，深夜路边的那股香。",
    shopKeyword: "烤串",
  },
  {
    id: "korean-bbq",
    name: "韩式烤肉",
    entityType: "dining_style",
    emoji: "🥓",
    kind: "main",
    cuisine: "korean",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["高热量", "解馋", "高蛋白"],
    meals: ["dinner"],
    recommend: 4,
    description: "五花肉用生菜包着吃，边烤边聊很热闹。",
  },
  {
    id: "japanese-yakiniku",
    name: "日式烧肉",
    entityType: "dining_style",
    emoji: "🥩",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高蛋白", "解馋", "高热量"],
    meals: ["dinner"],
    recommend: 4,
    description: "和牛轻轻一烤蘸点酱，入口即化。",
  },
  {
    id: "clay-stove-bbq",
    name: "泥炉烤肉",
    entityType: "dining_style",
    shopKeyword: "泥炉烤肉",
    emoji: "🔥",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["解馋", "高热量"],
    meals: ["dinner", "midnight"],
    recommend: 3,
    description: "炭火泥炉自己烤，烟火气十足。",
  },
  {
    id: "wanzhou-grilled-fish",
    name: "万州烤鱼",
    entityType: "dining_style",
    shopKeyword: "万州烤鱼",
    emoji: "🐟",
    kind: "main",
    cuisine: "cn-chuanyu",
    role: "main",
    priceTier: "treat",
    spicy: 2,
    tags: ["解馋", "下饭", "高热量"],
    regions: ["chuanyu"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "先烤后炖，麻辣鱼配配菜，宵夜很合适。",
  },
  {
    id: "self-bbq-buffet",
    name: "自助烤肉",
    entityType: "dining_style",
    shopKeyword: "自助烤肉",
    emoji: "🍖",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["高热量", "解馋", "高蛋白"],
    meals: ["dinner"],
    recommend: 3,
    description: "放开了吃，约朋友一起最划算。",
  },
  {
    id: "sukiyaki",
    name: "日式寿喜烧",
    entityType: "dining_style",
    emoji: "🍲",
    kind: "main",
    cuisine: "japanese",
    role: "main",
    priceTier: "treat",
    spicy: 0,
    tags: ["暖胃", "解馋", "高蛋白"],
    meals: ["dinner"],
    recommend: 4,
    description: "甜咸锅底涮肥牛，裹生蛋液入口即化。",
    shopKeyword: "日式料理",
  },
  {
    id: "budae-jjigae",
    name: "部队锅",
    entityType: "dining_style",
    emoji: "🍲",
    kind: "main",
    cuisine: "korean",
    role: "main",
    priceTier: "treat",
    spicy: 2,
    tags: ["暖胃", "解馋", "高热量"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "午餐肉、年糕、泡面一锅煮，越煮越香。",
    shopKeyword: "韩式料理",
  },
  // ===== 品牌/连锁店 brand（13）=====
  {
    id: "mcdonalds",
    name: "麦当劳",
    entityType: "brand",
    shopKeyword: "麦当劳",
    emoji: "🍟",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "快手"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "汉堡配薯条，熟悉又稳妥的一餐。",
  },
  {
    id: "kfc",
    name: "肯德基",
    entityType: "brand",
    shopKeyword: "肯德基",
    emoji: "🍗",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋", "快手"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "炸鸡汉堡随便配，馋了来一份。",
  },
  {
    id: "burger-king",
    name: "汉堡王",
    entityType: "brand",
    shopKeyword: "汉堡王",
    emoji: "🍔",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["高热量", "解馋"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "火烤厚牛肉饼，大口咬下去很过瘾。",
  },
  {
    id: "wallace",
    name: "华莱士",
    entityType: "brand",
    shopKeyword: "华莱士",
    emoji: "🍗",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["高热量", "解馋", "省钱"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "平价炸鸡汉堡，钱包友好。",
  },
  {
    id: "tastien",
    name: "塔斯汀中国汉堡",
    entityType: "brand",
    shopKeyword: "塔斯汀",
    emoji: "🍔",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "快手", "高热量"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 4,
    description: "现烤手擀堡胚，中式馅料挺有新意。",
  },
  {
    id: "saizeriya",
    name: "萨莉亚",
    entityType: "brand",
    shopKeyword: "萨莉亚",
    emoji: "🍝",
    kind: "main",
    cuisine: "western-italian",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "省钱"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "平价意式，几个人聚餐点一桌也不贵。",
  },
  {
    id: "shaxian-snack",
    name: "沙县小吃",
    entityType: "brand",
    shopKeyword: "沙县小吃",
    emoji: "🥟",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 0,
    tags: ["省钱", "快手", "暖胃"],
    meals: ["breakfast", "lunch", "dinner", "midnight"],
    recommend: 4,
    description: "拌面蒸饺炖罐，什么时候去都有得吃。",
  },
  {
    id: "laoxiangji",
    name: "老乡鸡",
    entityType: "brand",
    shopKeyword: "老乡鸡",
    emoji: "🐔",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "健康轻食", "下饭"],
    meals: ["lunch", "dinner"],
    recommend: 4,
    description: "老母鸡汤打底，家常快餐里的靠谱选择。",
  },
  {
    id: "yangguofu",
    name: "杨国福麻辣烫",
    entityType: "brand",
    shopKeyword: "杨国福麻辣烫",
    emoji: "🌶️",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 3,
    tags: ["解馋", "暖胃", "下饭"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "食材自选称重，麻酱一拌就很香。",
  },
  {
    id: "zhangliang",
    name: "张亮麻辣烫",
    entityType: "brand",
    shopKeyword: "张亮麻辣烫",
    emoji: "🌶️",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "budget",
    spicy: 3,
    tags: ["解馋", "暖胃", "下饭"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "红油白汤各有各的好，自选食材随你配。",
  },
  {
    id: "subway",
    name: "赛百味三明治",
    entityType: "brand",
    emoji: "🥪",
    kind: "main",
    cuisine: "western-american",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "快手", "清淡"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 3,
    description: "蔬菜现选现做，想清淡也行。",
    shopKeyword: "赛百味",
  },
  {
    id: "familymart-bento",
    name: "全家轻食便当",
    entityType: "brand",
    emoji: "🍱",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["快手", "健康轻食", "清淡"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 3,
    description: "加热即食，赶时间时便利店里随手一份。",
    shopKeyword: "全家便利店",
  },
  {
    id: "lawson-bento",
    name: "罗森轻食便当",
    entityType: "brand",
    emoji: "🍱",
    kind: "main",
    cuisine: "cn-generic",
    role: "main",
    priceTier: "normal",
    spicy: 0,
    tags: ["快手", "健康轻食", "清淡"],
    meals: ["breakfast", "lunch", "dinner"],
    recommend: 3,
    description: "饭团便当都有，深夜也买得到。",
    shopKeyword: "罗森便利店",
  },
  // ===== 饮品 drink（33）=====
  {
    id: "milk-tea",
    name: "珍珠奶茶",
    entityType: "dish",
    emoji: "🧋",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "续命"],
    meals: ["lunch", "dinner", "midnight", "tea"],
    recommend: 5,
    description: "三分糖少冰，一杯喝得很满足。",
  },
  {
    id: "americano",
    name: "美式咖啡",
    entityType: "dish",
    emoji: "☕",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["提神", "健康轻食"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 4,
    description: "苦中带香，提神醒脑的一杯。",
  },
  {
    id: "latte",
    name: "拿铁",
    entityType: "dish",
    emoji: "🥛",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["提神", "解馋"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 4,
    description: "喝不惯美式的话，加奶就柔和多了。",
  },
  {
    id: "cola",
    name: "冰可乐",
    entityType: "dish",
    emoji: "🥤",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "解馋", "续命"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "冰冰凉凉，配炸鸡最搭。",
    shopKeyword: "便利店",
  },
  {
    id: "soy-milk",
    name: "豆浆",
    entityType: "dish",
    emoji: "🥛",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "健康轻食", "暖胃"],
    meals: ["breakfast"],
    recommend: 3,
    description: "朴实又健康，配油条更香。",
  },
  {
    id: "suanmeitang",
    name: "酸梅汤",
    entityType: "dish",
    emoji: "🧃",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "清淡"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 4,
    description: "吃完辣的来一杯，瞬间解腻。",
  },
  {
    id: "coconut-water",
    name: "椰子水",
    entityType: "dish",
    emoji: "🥥",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "清淡"],
    meals: ["breakfast", "lunch", "dinner", "midnight"],
    recommend: 3,
    description: "清甜补水，想喝点健康的就选它。",
    shopKeyword: "便利店",
  },
  {
    id: "lemon-tea",
    name: "柠檬茶",
    entityType: "dish",
    emoji: "🍋",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "提神", "解馋"],
    meals: ["lunch", "dinner", "midnight", "tea"],
    recommend: 4,
    description: "酸爽解腻，油腻过后来一杯很舒服。",
  },
  {
    id: "yogurt",
    name: "酸奶",
    entityType: "dish",
    emoji: "🥛",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "清淡", "暖胃"],
    meals: ["breakfast", "lunch", "dinner", "midnight"],
    recommend: 3,
    description: "助消化又顶饱，嘴馋时的轻负担选择。",
  },
  {
    id: "hot-milk",
    name: "热牛奶",
    entityType: "dish",
    emoji: "🥛",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "暖胃", "健康轻食"],
    meals: ["breakfast", "midnight"],
    recommend: 3,
    description: "睡前一杯，暖暖的助眠。",
    shopKeyword: "便利店",
  },
  {
    id: "orange-juice",
    name: "鲜榨橙汁",
    entityType: "dish",
    emoji: "🍊",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "解腻", "提神"],
    meals: ["breakfast", "lunch"],
    recommend: 4,
    description: "维C满满，一口酸甜唤醒早晨。",
  },
  {
    id: "mango-pomelo-sago",
    name: "杨枝甘露",
    entityType: "dish",
    emoji: "🥭",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "解腻"],
    meals: ["lunch", "dinner", "midnight", "tea"],
    recommend: 4,
    description: "芒果西柚加西米，港式甜品里的人气款。",
  },
  {
    id: "hot-cocoa",
    name: "热可可",
    entityType: "dish",
    emoji: "☕",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "暖胃", "续命"],
    meals: ["breakfast", "dinner", "midnight", "tea"],
    recommend: 3,
    description: "冬夜捧着一杯，甜到心里。",
  },
  {
    id: "jasmine-tea",
    name: "茉莉花茶",
    entityType: "dish",
    emoji: "🍵",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "解腻", "健康轻食"],
    meals: ["breakfast", "lunch", "dinner", "midnight", "tea"],
    recommend: 3,
    description: "清香解腻，饭后来一杯很清爽。",
  },
  {
    id: "sprite",
    name: "雪碧",
    entityType: "dish",
    emoji: "🥤",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "解馋", "续命"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "透心凉，吃辣之后的灭火器。",
    shopKeyword: "便利店",
  },
  {
    id: "matcha-latte",
    name: "抹茶拿铁",
    entityType: "dish",
    emoji: "🍵",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["提神", "解馋"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 4,
    description: "微苦回甘，颜色好看味道也清新。",
  },
  {
    id: "mung-bean-soup",
    name: "绿豆沙",
    entityType: "dish",
    emoji: "🥤",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "清淡", "健康轻食"],
    meals: ["lunch", "dinner", "midnight"],
    recommend: 3,
    description: "夏天消暑，绵密一口很凉快。",
  },
  {
    id: "sparkling-water",
    name: "气泡水",
    entityType: "dish",
    emoji: "💧",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "解腻", "清淡"],
    meals: ["breakfast", "lunch", "dinner", "midnight"],
    recommend: 3,
    description: "零负担解腻，喝一口很舒服。",
    shopKeyword: "便利店",
  },
  {
    id: "honey-grapefruit-tea",
    name: "蜂蜜柚子茶",
    entityType: "dish",
    emoji: "🍯",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["清淡", "解腻", "暖胃"],
    meals: ["breakfast", "dinner", "midnight", "tea"],
    recommend: 3,
    description: "酸甜温润，喉咙不舒服时来一杯。",
  },
  {
    id: "oat-latte",
    name: "燕麦拿铁",
    entityType: "dish",
    emoji: "🥛",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["提神", "健康轻食"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 3,
    description: "植物奶更清爽，乳糖不耐也能喝。",
  },
  {
    id: "fruit-tea",
    name: "水果茶",
    entityType: "dish",
    emoji: "🍑",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "解馋", "健康轻食"],
    meals: ["tea", "lunch", "dinner"],
    recommend: 4,
    description: "满杯水果料，酸甜多汁。",
  },
  {
    id: "smoothie",
    name: "莓果奶昔",
    entityType: "dish",
    emoji: "🫐",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "解馋"],
    meals: ["tea", "breakfast"],
    recommend: 3,
    description: "莓果打成绵密一杯，好看又好喝。",
  },
  {
    id: "hong-dou-sha",
    name: "红豆沙",
    entityType: "dish",
    emoji: "🍵",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "暖胃"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "绵软香甜，喝完整个人暖暖的。",
  },
  {
    id: "chocolate-shake",
    name: "巧克力奶昔",
    entityType: "dish",
    emoji: "🍫",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "续命"],
    meals: ["tea", "midnight"],
    recommend: 3,
    description: "浓郁巧克力配冰淇淋，甜党会喜欢。",
  },
  {
    id: "coconut-latte",
    name: "生椰拿铁",
    entityType: "dish",
    emoji: "🥥",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["提神", "解馋"],
    meals: ["breakfast", "lunch", "tea"],
    recommend: 5,
    description: "椰香裹着咖啡，喝着顺口又解乏。",
  },
  {
    id: "yashixiang-lemon-tea",
    name: "鸭屎香柠檬茶",
    entityType: "dish",
    emoji: "🍋",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "提神", "解馋"],
    meals: ["lunch", "tea", "dinner"],
    recommend: 5,
    description: "鸭屎香单丛打底，茶香和柠檬都很足。",
  },
  {
    id: "handmade-lemon-tea",
    name: "手打柠檬茶",
    entityType: "dish",
    emoji: "🍋",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "提神", "解馋"],
    meals: ["lunch", "tea", "dinner", "midnight"],
    recommend: 4,
    description: "捶打出柠檬清香，酸爽又解腻。",
  },
  {
    id: "fresh-juice",
    name: "鲜榨纯果汁",
    entityType: "dish",
    emoji: "🧃",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["健康轻食", "解腻", "清淡"],
    meals: ["breakfast", "tea"],
    recommend: 3,
    description: "无添加现榨，维C满满一整杯。",
  },
  {
    id: "craft-beer",
    name: "精酿啤酒",
    entityType: "dish",
    emoji: "🍺",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解腻", "解馋", "续命"],
    meals: ["dinner", "midnight"],
    recommend: 4,
    description: "花果香浓郁，配烧烤小龙虾正好。",
  },
  {
    id: "fruit-wine",
    name: "果酒",
    entityType: "dish",
    emoji: "🍷",
    kind: "drink",
    cuisine: "cn-generic",
    role: "snack",
    priceTier: "normal",
    spicy: 0,
    tags: ["解馋", "解腻"],
    meals: ["dinner", "midnight"],
    recommend: 3,
    description: "果香微醺，小酌一杯不上头。",
  },
  {
    id: "thai-milk-tea",
    name: "泰式手标奶茶",
    entityType: "dish",
    emoji: "🧡",
    kind: "drink",
    cuisine: "thai",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "续命"],
    meals: ["lunch", "tea", "dinner"],
    recommend: 4,
    description: "橙红浓奶茶甜得带劲，配辣菜解辣。",
  },
  {
    id: "ramune",
    name: "日式弹珠汽水",
    entityType: "dish",
    emoji: "🥤",
    kind: "drink",
    cuisine: "japanese",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解腻", "解馋"],
    meals: ["lunch", "tea", "dinner", "midnight"],
    recommend: 3,
    description: "压下弹珠咕嘟冒泡，清爽带回忆杀。",
  },
  {
    id: "banana-milk",
    name: "韩式香蕉牛奶",
    entityType: "dish",
    emoji: "🍌",
    kind: "drink",
    cuisine: "korean",
    role: "snack",
    priceTier: "budget",
    spicy: 0,
    tags: ["解馋", "续命", "健康轻食"],
    meals: ["breakfast", "tea", "midnight"],
    recommend: 3,
    description: "胖胖瓶装香蕉奶，香甜顺滑很解馋。",
  },

];

/** 仅主食（老虎机前两轴用） */
export const mainFoods: Food[] = foods.filter((f) => f.kind === "main");

/** 仅饮品（老虎机第三轴用） */
export const drinkFoods: Food[] = foods.filter((f) => f.kind === "drink");

/** 取某餐段的主食池 */
export function mainFoodsByMeal(meal: MealType): Food[] {
  return mainFoods.filter((f) => f.meals.includes(meal));
}

/** 取某餐段的饮品池 */
export function drinkFoodsByMeal(meal: MealType): Food[] {
  return drinkFoods.filter((f) => f.meals.includes(meal));
}
